name: gimig_gastro_master
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  firebase_analytics: ^5.0.6

  connectivity: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - images/


  fonts:
   - family: Roboto
     fonts:
       - asset: fonts/Roboto-Regular.ttf
       - asset: fonts/Roboto-Italic.ttf
         style: italic
       - asset: fonts/Roboto-Bold.ttf
         weight: 700
